<?php

namespace SV\TitleEditHistory\XF\Service\Thread;



/**
 * Extends \XF\Service\Thread\Editor
 */
class Editor extends XFCP_Editor
{
    /**
     * @return \XF\Entity\Thread
     */
    protected function _save()
    {
        return parent::_save(); // TODO: Change the autogenerated stub
    }
}
